- name: Deploy Terraform infrastructure
  hosts: payment_servers
  gather_facts: false

  tasks:
    - name: Terraform init
      command: terraform init
      args:
        chdir: ../terraform-aws-lab

    - name: Terraform apply
      command: terraform apply -auto-approve
      args:
        chdir: ../terraform-aws-lab
