---
- name: Terraform Apply
  hosts: payment_servers
  gather_facts: false

  tasks:
    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: "{{ playbook_dir }}/../terraform-aws-lab"

    - name: Apply Terraform configuration
      command: terraform apply -auto-approve
      args:
        chdir: "{{ playbook_dir }}/../terraform-aws-lab"
